server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dt?useSSL=false
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
