server:
  port: 7080
#spring:
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/dt
#    password: password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

